#!/usr/bin/env bash 
sbatch slurm/slurm.1.txt
sbatch slurm/slurm.2.txt
sbatch slurm/slurm.3.txt
sbatch slurm/slurm.4.txt
sbatch slurm/slurm.5.txt
sbatch slurm/slurm.6.txt
sbatch slurm/slurm.7.txt
sbatch slurm/slurm.8.txt
sbatch slurm/slurm.9.txt
sbatch slurm/slurm.10.txt
sbatch slurm/slurm.11.txt
sbatch slurm/slurm.12.txt
sbatch slurm/slurm.13.txt
sbatch slurm/slurm.14.txt
sbatch slurm/slurm.15.txt
sbatch slurm/slurm.16.txt
sbatch slurm/slurm.17.txt
sbatch slurm/slurm.18.txt
sbatch slurm/slurm.19.txt
sbatch slurm/slurm.20.txt
sbatch slurm/slurm.21.txt
sbatch slurm/slurm.22.txt
sbatch slurm/slurm.23.txt
sbatch slurm/slurm.24.txt
sbatch slurm/slurm.25.txt
sbatch slurm/slurm.26.txt
sbatch slurm/slurm.27.txt
sbatch slurm/slurm.28.txt
sbatch slurm/slurm.29.txt
sbatch slurm/slurm.30.txt
sbatch slurm/slurm.31.txt
sbatch slurm/slurm.32.txt
sbatch slurm/slurm.33.txt
sbatch slurm/slurm.34.txt
sbatch slurm/slurm.35.txt
sbatch slurm/slurm.36.txt
