
import tensorflow as tf
from train import *

LIST_LEARNING_RATES = [0.001]
LIST_FILTER_SIZES = ["3,4,5"]
LIST_NUM_FILTERS = [64]
LIST_DROPOUT_KEEP_PROB = [0.5]

LIST_L2_REG_LAMBDA = [1e-3, 1e-4, 1e-5]
LIST_BATCH_SIZE = [64, 128, 256]
LIST_NUM_EPOCHS = [100, 200, 300]

def main(_):
    trains(LIST_LEARNING_RATES, LIST_FILTER_SIZES, LIST_NUM_FILTERS, LIST_DROPOUT_KEEP_PROB, LIST_L2_REG_LAMBDA, LIST_BATCH_SIZE, LIST_NUM_EPOCHS)


if __name__ == '__main__':
    tf.app.run()

